### ISSUE TITLE
DV-custom character-API

### ISSUE THREAD

**Issue by Spacialist** [VRGuild/VRGuild#100]
USTRUCT(BlueprintType, Atomic)
struct FCharacterCustomDataAPI
{
	GENERATED_USTRUCT_BODY()
public:
	FCharacterCustomDataAPI() {};
	UPROPERTY(BlueprintReadOnly)
	TArray<int> status;
};

API 로 받아야하는 정보: 
```c++
struct CharacterCreate {
	private int[] status;
}

struct CharacterModify {
	private Long characterId;
	private int[] status;
}
```
 
 ## 주소
헤더 추가("Authorization" : "Bearer [token]")

캐릭터 생성 : POST http://125.132.216.190:15530/api/character
캐릭터 조회 : GET http://125.132.216.190:15530/api/character
캐릭터 조회 : PATCH
http://125.132.216.190:15530/api/character
캐릭터 조회 : DELETE
http://125.132.216.190:15530/api/character

**Comment by liebespaar93** [comment]
@Spacialist 
http://125.132.216.190:15530/swagger-ui/index.html#/user-character-controller/getCharacter
이거보면 
```cpp
{
  "characterId": 0,
  "accountId": "string",
  "status": [
    0
  ]
}
```
이렇게 되있어서 받을떄 바꿔야함
